version: '3'

services:
  dev:
    container_name: eruption-dev
    build:
      dockerfile: dockerfile.dev
    ports:
      - '3000:3000'
    # working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # command: npm run dev
