name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node and install project dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}    
      
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      #- name: Test
      #  run: cd packages/web && npm run test

      - name: Build
        run: npm run build
