name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'packages/functions/**'
      - '.github/workflows/cloud_functions.yml'

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Deploy to Firebase Functions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node and install project dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}    
      
      - name: Install dependencies
        run: npm install

      - name: Auth GC
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

      - name: Deploy
        env:
          VITE_RANDOM_SEED: ${{ secrets.VITE_RANDOM_SEED }}
          VITE_SECRET_TOKEN: ${{ secrets.VITE_SECRET_TOKEN }}
          VITE_DISCORD_API_URL: ${{ secrets.VITE_DISCORD_API_URL }}
          VITE_DISCORD_CLIENT_ID: ${{ secrets.VITE_DISCORD_CLIENT_ID }}
          VITE_DISCORD_BOT_TOKEN: ${{ secrets.VITE_DISCORD_BOT_TOKEN }}
          VITE_DISCORD_REDIRECT_URI: ${{ secrets.VITE_DISCORD_REDIRECT_URI }}
          VITE_DISCORD_CLIENT_SECRET: ${{ secrets.VITE_DISCORD_CLIENT_SECRET }}

        run: |
          npm run global:build
          npm install -g firebase-tools

          echo "VITE_RANDOM_SEED=$VITE_RANDOM_SEED" > packages/functions/.env
          echo "VITE_SECRET_TOKEN=$VITE_SECRET_TOKEN" >> packages/functions/.env
          echo "VITE_DISCORD_API_URL=$VITE_DISCORD_API_URL" >> packages/functions/.env
          echo "VITE_DISCORD_CLIENT_ID=$VITE_DISCORD_CLIENT_ID" >> packages/functions/.env
          echo "VITE_DISCORD_BOT_TOKEN=$VITE_DISCORD_BOT_TOKEN" >> packages/functions/.env
          echo "VITE_DISCORD_REDIRECT_URI=$VITE_DISCORD_REDIRECT_URI" >> packages/functions/.env
          echo "VITE_DISCORD_CLIENT_SECRET=$VITE_DISCORD_CLIENT_SECRET" >> packages/functions/.env

          npm run functions:deploy

          rm packages/functions/.env
